### ISSUE TITLE
Exception while connection on Fedora 39 - Python 3.12

### ISSUE THREAD

**Issue by Exiled1** [mahaloz/decomp2dbg#82] opened 2023-12-29 05:23 UTC
Versions:
- GDB: 13.2
- Pwndbg: 2023.07.17 build: e230a85
- GEF: GEF: rev:951872bd965d8748ae94c75c619e396fbfc8e01b (Git - clean)
- Binary Ninja: 3.5.4526 Personal
Challenge: (Death Note) https://pwnable.tw/challenge/#10
- Environment: [Kali virtual machine](https://www.kali.org/get-kali/#kali-virtual-machines)

Potentially strange environment configurations: I am currently using this script to be able to swap between gdb versions
- https://github.com/apogiatzis/gdb-peda-pwndbg-gef

Behavior: After setting up the RPC server to localhost with the default port, 
![image](https://github.com/mahaloz/decomp2dbg/assets/24551877/d74f64a7-7d8d-484a-b5ed-f52518dfd169)

And after confirming that there was a listening service on 127.0.0.1:
![image](https://github.com/mahaloz/decomp2dbg/assets/24551877/9d6781b6-8c44-4092-9a64-22fb685dde42)

I use the command `gdb-pwndbg ./death_note` (Should be the same thing as gdb with pwndbg installed), and use the following commands:
- `b main`
- `entry`
- `decompiler connect binja --host 127.0.0.1 --port 3662`
To which I receive the response"
- `Python Exception <class 'TypeError'>: expected string or bytes-like object, got 'list'
Error occurred in Python: expected string or bytes-like object, got 'list'`
![image](https://github.com/mahaloz/decomp2dbg/assets/24551877/ea3e8d88-6f8f-49e4-90a3-f59587d7c957)

The same error occurs when I use GEF, and GDB, 
GEF:
![image](https://github.com/mahaloz/decomp2dbg/assets/24551877/ae45b50d-ee88-4005-9e4c-d733e56f55ff)

GDB:
![image](https://github.com/mahaloz/decomp2dbg/assets/24551877/9e4e8bcc-6c86-4324-9bd4-ff1bff7e002a)

If you would like me to modify my environment to troubleshoot, I absolutely can :).

**Comment by mahaloz** [comment] 2023-12-29 19:24
Hi @Exiled1, would you be able to provide your Python version? Using this binary on Ubuntu 22.04, which has Python 3.10, I was unable to reproduce this bug :(. My best guess is you have a rather old Python version that changed how one of the library calls work

**Comment by Exiled1** [comment] 2023-12-29 20:30
Hello! I actually have Python 3.11.7 installed on this machine, would that be a problem?

![image](https://github.com/mahaloz/decomp2dbg/assets/24551877/44da6872-40c5-4c49-bb12-cebc3d3aa23c)

**Comment by mahaloz** [comment] 2024-01-04 01:39
So it turns out this was fixed in https://github.com/mahaloz/decomp2dbg/commit/60822010a98e69c338211f928f2270960fc5a313, but the Python pip remote was not updated... ha! However, we also fixed it by installing `binutils gcc`. Should this bug reappear, it's due to those not being installed.

**Closed by mahaloz** 2024-01-04 01:39 UTC
